#!/bin/bash

jarname=SafeSpawn-0.1b.jar

cp config.yml ./bin
cp plugin.yml ./bin
cd ./bin

if [ -e $jarname ]; then
  rm $jarname
fi

jar cf $jarname config.yml plugin.yml com ../libs
rm config.yml plugin.yml
push_bukkit $jarname
