# default config.yml
# zone.radius has a max of 200
welcome_message: Welcome to Zulu, please read /gamedesc and the /rules thanks.
worlds:
  world:
    name: world
    magic: oh
  world_nether:
    name: world_nether
    magic: ne
  world_the_end:
    name: world_the_end
    magic: de
spawnpoint:
  world: world
  x: 50
  y: 65
  z: 330 
gamedesc:
  - Welcome to Zulu -
  - I started this server after getting in a motorcycle accident and got bored laying in bed.  When they wheeled me into the ER they didnt know my name so they gave me a temporary name of Zulu so it seemed fitting.
  - This may appear to be plain old vanilla server but it isnt.
  - I am a software engineer and in my boredom I have written my own plugin for this world with many mysterious and awesome magic tricks for you to discover.
  - The spawn area you have started in is in a protection bubble 200 wide.  You cant move blocks and monsters cant hurt you here.
  - GameMode is Survival
  - PVP is off during the day and on at night.
  - Hardcore is off, if you die you return to spawn.
  - Difficulty = normal.
  - Enjoy the world, and new features are coming.
rules:
  - 1. Dont be a dick.
  - 2. Dont ask to change the server settings.
  - 3. Obey the rules.
casthelp:
  - Make a teleporter!
  - Lock your stuff in a chest!
  - Claim land and protect it!
  - For more info visit:
  - http://176.31.140.130:8080/Public/zulu.html
zones:
  zone0:
    description: Iron Spawn 
    exclude:
      - BLOCK_BREAK
      - BLOCK_PLACE
      - PLAYER_DMG_FROM_ENTITY
      - BADDIE_SPAWN
    radius: 100 
    world: world
    x: 50
    y: 65
    z: 330 
  zone1:
    description: Emerald City
    exclude:
      - BLOCK_BREAK
      - BLOCK_PLACE
      - PLAYER_DMG_FROM_ENTITY
      - BADDIE_SPAWN
    radius: 35 
    world: world
    x: 14
    y: 66
    z: 1306 
  zone2:
    description: Iron Pyramid
    exclude:
      - BLOCK_BREAK
      - BLOCK_PLACE
      - PLAYER_DMG_FROM_ENTITY
      - BADDIE_SPAWN
    radius: 35  
    world: world
    x: 114 
    y: 63
    z: 2255 