# default config.yml
# zone.radius has a max of 200
welcome_message: Please read and obey the /rules
worlds:
  world:
    name: world
    magic: oh
  world_nether:
    name: world_nether
    magic: ne
  world_the_end:
    name: world_the_end
    magic: de
spawnradius: 5
spawnpoint:
  world: world
  x: 50
  y: 65
  z: 330 
gamedesc:
  - Im experimenting with my own plugins so I apologize for instability.
  - GameMode = Survival, unless youre helping the Op with something.
  - PVP = false, however Im working enabling it upon request.
  - Hardcore = false
  - Difficulty = normal
rules:
  - Dont ask to change the server or game config, its just the way I like it. 
  - Dont push others into lava.
  - Dont mess up the spawn area.
  - Id prefer you re-plant trees you chop down.
  - Obey the rules.
zones:
  zone0:
    description: Test zone
    exclude:
      - BLOCK_BREAK
      - BLOCK_PLACE
      - PLAYER_DMG_FROM_ENTITY
    radius: 100 
    world: world
    x: 50
    y: 65
    z: 330 