name: SafeSpawn
main: com.ath.bukkit.safespawn.SafeSpawn
version: 0.1 Beta
author: angryBits
description: My own special blend of tools for running a minecraft server
database: true
commands:
  gamedesc:
    description: How the server is configured
    permission: safespawn.gamedesc
    permission-message: You don't have permission
  rules:
    description: Rules for the server
    permission: safespawn.rules
    permission-message: You don't have permission
  spawn:
    description: Return to the spawn area.
    permission: safespawn.spawn
    permission-message: You don't have that ability
  cast:
    description: Magically enhances blocks and actions
    permission: safespawn.magic.cast
    permission-message: You don't have that ability
  casthelp:
    description: Explains how to cast magic
    permission: safespawn.magic.cast
    permission-message: You don't have that ability
  nick:
    description: Change your player name.
